version: '3.4'

services:
  consul:
    ports:
         - "8500:8500"

  coupon_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.coupon
      - ServiceConfig__Name=CouponService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=coupon_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
    ports:
      - "5200:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - consul

  authentication_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.authentication
      - ServiceConfig__Name=AuthenService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=authentication_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
    ports:
      - "5300:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - consul

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5400:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
        - consul
        - authentication_service
        - coupon_service
