version: '3.4'

services:
  consul:
     image: consul:1.15.4
     command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
     hostname: consul
     container_name: consul
     networks:
         - common_network

  coupon_service:
    container_name: couponservice
    image: ${DOCKER_REGISTRY-}fttravelakoservicescouponapi
    restart: on-failure
    hostname: localhost
    build:
      context: .
      dockerfile: FT.Travelako.Services.CouponAPI/Dockerfile
    networks:
      - common_network

  authentication_service:
    container_name: authenservice
    image: ${DOCKER_REGISTRY-}fttravelakoservicesauthentication
    restart: on-failure
    hostname: localhost
    build:
      context: .
      dockerfile: FT.Travelako.Services.Authentication/Dockerfile
    networks:
      - common_network


  ocelotapigw:
    container_name: ocelot.gateway
    image: ${DOCKER_REGISTRY-}fttravelakoocelotapigw
    restart: on-failure
    hostname: localhost
    build:
      context: .
      dockerfile: FT.Travelako.OcelotApiGw/Dockerfile
    networks:
      - common_network

networks:
    common_network:
        driver: bridge