version: '3.4'

services:
  consul:
     image: consul:1.15.4
     command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
     hostname: consul
     container_name: consul
     networks:
         - common_network

  cachedb:
    image: redis/redis-stack:latest

  # traveldb:
  #    image: mcr.microsoft.com/mssql/server:2022-latest

  # portainer:
  #   image: portainer/portainer-ce


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.9.2

  coupon_service:
    container_name: couponservice
    image: ${DOCKER_REGISTRY-}fttravelakoservicescouponapi
    restart: on-failure
    hostname: coupon_service
    build:
      context: .
      dockerfile: Services/FT.Travelako.Services.CouponAPI/Dockerfile
    networks:
      - common_network

  authentication_service:
    container_name: authenservice
    image: ${DOCKER_REGISTRY-}fttravelakoservicesauthentication
    restart: on-failure
    hostname: authentication_service
    build:
      context: .
      dockerfile: Services/FT.Travelako.Services.Authentication/Dockerfile
    networks:
      - common_network

  travel_service:
    container_name: travelservice
    image: ${DOCKER_REGISTRY-}fttravelakoservicestravelapi
    restart: on-failure
    hostname: travel_service
    build:
      context: .
      dockerfile: Services/FT.Travelako.Services.TravelAPI/Dockerfile
    networks:
      - common_network

  ocelotapigw:
    container_name: ocelot.gateway
    image: ${DOCKER_REGISTRY-}fttravelakoocelotapigw
    restart: on-failure
    hostname: localhost
    build:
      context: .
      dockerfile: ApiGateway/FT.Travelako.OcelotApiGw/Dockerfile
    networks:
      - common_network

networks:
    common_network:
        driver: bridge

# volumes:
#   portainer_data:
#   elasticsearch-data: