version: '3.4'

services:
  consul:
    ports:
     - "8500:8500"

  # traveldb:
  #   container_name: traveldb
  #   restart: always 
  #   environment:
  #    - ACCEPT_EULA=Y
  #    - MSSQL_SA_PASSWORD=123456aA@
  #   ports:
  #        - "1433:1433"

  cachedb:
    container_name: cachedb
    restart: always    
    ports:
        - "6379:6379"
        - "8001:8001"

  user_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.user
      - ServiceConfig__Name=UserService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=user_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5700:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - consul
      # - traveldb

  booking_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.booking
      - ServiceConfig__Name=BookingService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=booking_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5600:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - consul
      # - traveldb

  travel_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.travel
      - ServiceConfig__Name=TravelService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=travel_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5500:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - consul
      # - traveldb
       
  coupon_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.coupon
      - ServiceConfig__Name=CouponService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=coupon_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5200:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - consul
      # - traveldb 

  authentication_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ServiceConfig__Id=Service.authentication
      - ServiceConfig__Name=AuthenService
      - ServiceConfig__DiscoveryAddress=http://consul:8500
      - ServiceConfig__Address=authentication_service
      - ServiceConfig__Port=80
      - ServiceConfig__HealthCheckEndPoint=healthcheck
      - "DatabaseSettings:ConnectionString=Server=traveldb;Port=5432;Database=TravelDb;User Id=sa;Password=123456aA@;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "5300:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - consul
      # - traveldb 


  web_app:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=80
        - "ApiSettings:GatewayAddress=http://ocelotapigw"
        - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - ocelotapigw
        - authentication_service
        - coupon_service
        - travel_service
    ports:
        - "5800:80"

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      # - ASPNETCORE_URLS=http://+:80
    ports:
      - "5400:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
        - consul
        - authentication_service
        - coupon_service
        - travel_service

  # portainer:
  #   container_name: portainer
  #   restart: always
  #   ports:
  #     - "8080:8000"
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  # elasticsearch:
  #   container_name: elasticsearch
  #   environment:
  #       - xpack.monitoring.enabled=true
  #       - xpack.watcher.enabled=false
  #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #       - discovery.type=single-node
  #   ports:
  #       - "9200:9200"
  #   volumes:
  #       - elasticsearch-data:/usr/share/elasticsearch/data   

  # kibana:
  #   container_name: kibana
  #   environment:        
  #       - ELASTICSEARCH_URL=http://elasticsearch:9200
  #   depends_on:
  #       - elasticsearch
  #   ports:
  #       - "5601:5601" 
